### PR TITLE
Fix for web2 cors setting

### PR DESCRIPTION
**Pull request by EugeneTeu**
We need to spoof the browser headings when sending requests

### CODE REVIEW

**Comment by nikohd12** [comment]
Hello @EugeneTeu ,

Thank you for the hotfix. I can confirm that this is working. Will continue to test and report back.

**Comment by EugeneTeu** [comment]
@oneskill @nikohd12 what strategies are you guys running? theres some changes to the tavern api.

**Comment by EugeneTeu** [comment]
@oneskill @nikohd12 what strategies are you guys running? theres some changes to the tavern api.

**Comment by nikohd12** [comment]
> @oneskill @nikohd12 what strategies are you guys running? theres some changes to the tavern api.

HighestMpCost and HighestMp. I have updated the limit to 100 too. Will report back. But it worked earlier when it was 200.

**Comment by EugeneTeu** [comment]
@nikohd12 ah it failed for me cause i set the limit to 500. I have updated the `HighestMp` strategy cause it seems like it was querying by `price`

**Comment by EugeneTeu** [comment]
@nikohd12 ah it failed for me cause i set the limit to 500. I have updated the `HighestMp` strategy cause it seems like it was querying by `price`

**Comment by oneskill** [comment]
@EugeneTeu  I'm running HighestBpCost and HighestMpCost. It was failing for me too since the API change, I was running at 300, but move to 100, and it seems to work well.

**Comment by coccoinomane** [comment]
Thank you @EugeneTeu for the sleuthing and for the hotfix!

Will merge as soon as I get home (currently in Wien's airport 😅).

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
> Thank you @EugeneTeu for the sleuthing and for the hotfix!
> 
> Will merge as soon as I get home (currently in Wien's airport 😅).
> 
> Cheers, Cocco



> Thank you @EugeneTeu for the sleuthing and for the hotfix!
> 
> Will merge as soon as I get home (currently in Wien's airport 😅).
> 
> Cheers, Cocco

Hey no problem,

by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha

**Comment by EugeneTeu** [comment]
> Thank you @EugeneTeu for the sleuthing and for the hotfix!
> 
> Will merge as soon as I get home (currently in Wien's airport 😅).
> 
> Cheers, Cocco



> Thank you @EugeneTeu for the sleuthing and for the hotfix!
> 
> Will merge as soon as I get home (currently in Wien's airport 😅).
> 
> Cheers, Cocco

Hey no problem,

by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha

**Comment by doru15** [comment]
Hi @EugeneTeu 
I think that the query limit from HighestBp and HighestBpHighCost strategies must be changed to 100. With current value of 200 crabada idle api always returns an empty array.
Also nice catch with that `time_point` change.

**Comment by flazewang** [comment]
> > Thank you @EugeneTeu for the sleuthing and for the hotfix!
> > Will merge as soon as I get home (currently in Wien's airport 😅).
> > Cheers, Cocco
> 
> Hey no problem,
> 
> by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha.
> 
> This PR also has the changes from #60 , in a rush i committed the fix on the same branch



> > Thank you @EugeneTeu for the sleuthing and for the hotfix!
> > Will merge as soon as I get home (currently in Wien's airport 😅).
> > Cheers, Cocco
> 
> Hey no problem,
> 
> by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha.
> 
> This PR also has the changes from #60 , in a rush i committed the fix on the same branch

yep, I found this too, it points to time_point when uses Mine Points listing in tavern now...

**Comment by flazewang** [comment]
> > Thank you @EugeneTeu for the sleuthing and for the hotfix!
> > Will merge as soon as I get home (currently in Wien's airport 😅).
> > Cheers, Cocco
> 
> Hey no problem,
> 
> by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha.
> 
> This PR also has the changes from #60 , in a rush i committed the fix on the same branch



> > Thank you @EugeneTeu for the sleuthing and for the hotfix!
> > Will merge as soon as I get home (currently in Wien's airport 😅).
> > Cheers, Cocco
> 
> Hey no problem,
> 
> by the way it seems the api uses `time_point` instead of `mine_point` to query the reinforcements haha.
> 
> This PR also has the changes from #60 , in a rush i committed the fix on the same branch

yep, I found this too, it points to time_point when uses Mine Points listing in tavern now...

**Comment by coccoinomane** [comment]
Merged with master, thank you agan @EugeneTeu !

PS: I have reverted only one little change [here](https://github.com/coccoinomane/crabada.py/pull/65/commits/fb86d0666207dd75f84c3f65d35e62cc45dd2f76#diff-9c5b4819094e0624da71e05e1fcee6be2041c922601713f82b53c4ecf72edfa7R108), is that ok for you or you had a reason have open mines as default?

**Comment by EugeneTeu** [comment]
> Merged with master, thank you agan @EugeneTeu !
> 
> PS: I have reverted only one little change [here](https://github.com/coccoinomane/crabada.py/pull/65/commits/fb86d0666207dd75f84c3f65d35e62cc45dd2f76#diff-9c5b4819094e0624da71e05e1fcee6be2041c922601713f82b53c4ecf72edfa7R108), is that ok for you, or maybe you had a specific reason to return only `open` mines as default?


no reason, was debugging and comparing the API with the crabada site. Also the site uses `time_point` instead but `mine_point` seems to work as well...

**Comment by EugeneTeu** [comment]
> Merged with master, thank you agan @EugeneTeu !
> 
> PS: I have reverted only one little change [here](https://github.com/coccoinomane/crabada.py/pull/65/commits/fb86d0666207dd75f84c3f65d35e62cc45dd2f76#diff-9c5b4819094e0624da71e05e1fcee6be2041c922601713f82b53c4ecf72edfa7R108), is that ok for you, or maybe you had a specific reason to return only `open` mines as default?


no reason, was debugging and comparing the API with the crabada site. Also the site uses `time_point` instead but `mine_point` seems to work as well...

**Comment by coccoinomane** [comment]
Ah sorry, I understood your `time_point` commit the other way around! 
Will revert it :-)

**Pull request merged**
