### PR TITLE
Swimmer network

### PR DESCRIPTION
**Pull request by EugeneTeu**
added support for swimmer test network. 

Just needed to bypass `EIP-1559`  and build the transaction differently. it seems no plans for swimmer to implement EIP-1559 

```
  tx: TxParams = {
            'type': 0x1,
            'chainId': self.chainId,
            'gas': self.gasLimit,  # type: ignore
            'gasPrice':  25000000000,
            'nonce': self.getNonce(),
        }
```

for issue #7

### CODE REVIEW

**Comment by coccoinomane** [comment]
Thanks @EugeneTeu for all the tests and for the pull request... good find on the EIP-1559 caveat 👍

As for the implementation, we probably need a separate subclass of `Web3Client` named `SwimmerNetworkWeb3Client` which overrides stuff like chain ID and gas configuration; in turn, `CrabadaWeb3Client` will extend `SwimmerNetworkWeb3Client`.

In this way, we can keep `Web3Client` and `AvalancheCWeb3Client` clean, because they don't need to know about either Crabada or the Swimmer network.

Feel free to give it a go if you feel like it, otherwise I might do it myself next week.

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
Done. not sure if you could share your prettier/linting config for py? so that subsequent PR would not have the extra lines

**Comment by coccoinomane** [comment]
Hey @EugeneTeu , thanks for updating the branch with master.

Do you happen to know any detail on when will Crabada move over to Swimmer?
I wonder if the contracts on the C Chain will keep on working...

**Comment by EugeneTeu** [comment]
Hey @coccoinomane , https://medium.com/@PlayCrabada/introducing-crabadas-subnet-on-the-avalanche-network-18cb310ddb8c

according to this its end of march. And no the idle game contract should stop working? wonder if we could just create our own version of the crabada smart contract and continue on c-chain..... 

maybe name it cocoada. 
Screenshot 2022-03-20 at 10 32 12 AM

**Comment by coccoinomane** [comment]
Forking the C-Chain smart contract is a nice idea, although I would consider it only if thigs really get messy with the Swimmer migration. Let's put Coccoada on hold for a while ;-)

In general, let's wait for the Crabada team to divulge more details on the migration before further action.

**Comment by nikohd12** [comment]
> Hey @EugeneTeu , thanks for updating the branch with master.
> 
> Do you happen to know any detail on when will Crabada move over to Swimmer? I wonder if the contracts on the C Chain will keep on working...

Last I heard, it was end of March (not first week of April) despite the team encountering COVID-19 issues.

**Comment by EugeneTeu** [comment]
@coccoinomane gas fees has been updated for new alpha version of swimmer. Base fees is `4200000000000`

**Comment by yigitest** [comment]
Tried this on swimmer-testnet yesterday. I can confirm all mining functions are working except reinforce. 

```
Borrowing crab 120969 for mine xxxx at 1 TUS... [BP=222, MP=79]
Error reinforcing mine xxxx execution reverted: GAME:INVALID PRICE
```

But at the same time when I tried from website, I got same error for same crab. I don't think it's our fault. Good news is, we were able to detect the problem and revert execution before spending any TUS :)

**Comment by CBSInvest** [comment]
@EugeneTeu 
do we just have to update the settings of the new swimmer network in ur swimmer testnet breaking #8 ??
Over there we have the settings from the testnet, does someone has the real network information to be replaced there ?
Thx
Claus

**Comment by EugeneTeu** [comment]
> That sounds great @yigitest !
> 
> Will merge most likely this Friday.
> 
> Cheers, Cocco

hi @coccoinomane , likely will need to update the values here when bridged over to swimmer. I will be out of action for the next few days so my update might be slow.

**Comment by coccoinomane** [comment]
Thanks @EugeneTeu for the update, having an automatic estimate of `gasPrice` is very useful indeed :-)

In this very moment, I am refactoring the client to allow choosing Swimmer vs C-Chain directly in _.env_.
This should allow us to maintain compatibility with both networks while the "great migration" plays out.

Could you please confirm that the code in the PR currently has the correct Swimmer mainnet configuration?

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
hey @coccoinomane, yes i was able to sent a team to mine with the code in this PR on swimmer. Havent tested reinforcement + close game. Will report back later

**Comment by danvaneijck** [comment]
@EugeneTeu what do i use for the WEB3_NODE_URI ?

**Comment by danvaneijck** [comment]
im getting "no available teams"

**Comment by EugeneTeu** [comment]
> 

@danvaneijck update ur team numbers in the env file

**Comment by danvaneijck** [comment]
@EugeneTeu have done that. team 4205. am I using the right NODE_URI ? 
https://subnets.avax.network/swimmer/mainnet/rpc
or
https://rpc.swimmer.network/ext/bc/2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX/rpc

**Comment by EugeneTeu** [comment]
@danvaneijck https://subnets.avax.network/swimmer/mainnet/rpc im using this one. the node_uri should not affect that tho. is ur crabs available?

**Comment by danvaneijck** [comment]
@EugeneTeu yeah, is there any other reason id be getting that error? do i need to send them on one manually first

**Comment by coccoinomane** [comment]
> @EugeneTeu yeah, is there any other reason id be getting that error? do i need to send them on one manually first

I would expect that, as you need to allow spending of TUS on Swimmer before the bot can do anything.

**Comment by danvaneijck** [comment]
cool have tried that, will report back. TUS was already approved tho

**Comment by danvaneijck** [comment]
team on mine yup

**Comment by coccoinomane** [comment]
Quick update.

I have:

- Tested with success sending a team mining on the Swimmer network 🎉
- Wrote a draft Wiki article on the migration > https://github.com/coccoinomane/crabada.py/wiki/%5BDRAFT%5D-Swimmer-Network-migration
- Updated the Web3 client to support again both type-1 and type-2 txs

Will merge with master if I also manage to reinforce.

**Comment by coccoinomane** [comment]
Argh, nodoby's attacking me!

Come on guys, give me a test case... attack mine 6694 😂

**Comment by nikohd12** [comment]
> Argh, nodoby's attacking me!
> 
> Come on guys, give me a test case... attack mine 6694 😂

Haha! Thank you @yigitest @coccoinomane

**Comment by nikohd12** [comment]
I’ll test it out once I get home. Still at work on a Friday night

**Comment by nikohd12** [comment]
Closing and starting of mines working. Do not forget to change the team IDs, ppl. Haha!

**Comment by EugeneTeu** [comment]
cant reinforce, debbugging

**Comment by CBSInvest** [comment]
@coccoinomane send ur miner number and i give u an attack 
i was able to close the mining teams but cvant send them on the mine any reason why ? it says No available teams to send mining for user ......

**Comment by yigitest** [comment]
Thx @EugeneTeu 
Managed to call reinforceDefense function. 

_By the way, I accidentally opened a branch named pr-8 instead of pushing here. Ignore it._

**Comment by danvaneijck** [comment]
hey guys im dumb and was not on the right branch haha. Its working ! ty

**Comment by Mrooie** [comment]
Soooooo I was attacked on swimmer (already reinforced manually before) and there is an error reinforcing:

`src.common.logger - INFO - Strategy 'HighestMpFromInventory' could not find a suitable reinforcement for team 12238
src.common.logger - INFO - Borrowing crab 92046 for mine 35130 at 39.9 TUS... [BP=221, MP=81]
src.common.logger - WARNING - Error reinforcing mine 35130: execution reverted: GAME:INVALID PRICE`

**Comment by Mrooie** [comment]
Tested reinforcing - works like a charm. 🙏✨

Got me a little heart attack, when Debug printed:
`src.common.logger - DEBUG - Spent 1.97742 ETH`
I've never checked a blockchain explorer that fast. 🙈🤣🤣🤣 Obvs it's TUS. 🤣

Thank you!!!!

**Comment by norcsibaba** [comment]
Not working for me. I tried everything. Do I need all the pull request changes to make it work? I never used git, I don't know about it. The last change on the clonable project is 9 days old. The new changes are not there to clone.

**Comment by EugeneTeu** [comment]
@norcsibaba relax, these changes are not yet in the main branch. will be merged soon. thanks @yigitest !

**Comment by coccoinomane** [comment]
Great job guys!!! I feel the power of open source flowing strong in this project 🦀🔥🦀🔥🦀🔥🦀🔥🦀

As soon as I start a new mine, I will test the reinforce!

Then, before merging in `master`, I only need to fix the donation mechanism.

**Comment by coccoinomane** [comment]
Tests on my side worked succesfully: I am merging!

Thank you so much to @EugeneTeu for the PR and to @yigitest for the contriibutions... and to the community as a whole to provide precious feedback on the implementation 💪

**Pull request merged**
