### PR TITLE
add gas limit to start mine and close mine

### PR DESCRIPTION
**Pull request by EugeneTeu**
hi @coccoinomane, testing this out right now, decided to add a gas limit to the mine scripts so that you wont close a mine if the gwei is like 10000. (had edge case where 0.5A was spent)

### CODE REVIEW

**Comment by EugeneTeu** [comment]
if its ok, i can add to close Loot too

**Comment by EugeneTeu** [comment]
if its ok, i can add to close Loot too

**Comment by coccoinomane** [comment]
Thank you very much, @EugeneTeu ! Finer gas control  is certainly a welcome addition given the recent TUS price action 💪

Will merge to master and then focus on https://github.com/coccoinomane/crabada.py/pull/65.

**Comment by coccoinomane** [comment]
PS: Could you please check whether your editor correctly reads the settings in *pyproject.toml*?

It seems it is not respecting the following directive:

```
[tool.black]
line-length = 88
```

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
> 



> PS: Could you please check whether your editor correctly reads the settings in _pyproject.toml_?
> 
> It seems it is not respecting the following directive:
> 
> ```
> [tool.black]
> line-length = 88
> ```
> 
> Cheers, Cocco

ok, i ran black on the files in #65

**Comment by EugeneTeu** [comment]
> 



> PS: Could you please check whether your editor correctly reads the settings in _pyproject.toml_?
> 
> It seems it is not respecting the following directive:
> 
> ```
> [tool.black]
> line-length = 88
> ```
> 
> Cheers, Cocco

ok, i ran black on the files in #65

**Pull request merged**
