### PR TITLE
Add support for telegram notifications.

### PR DESCRIPTION
**Pull request by yigitest**
I've added support for [Telegram Messenger](https://telegram.org/). Users can create their own Telegram Bots to receive crabada-bot status updates.

* Additional environment varilables:

    ```
    NOTIFICATION_IM=1
    TELEGRAM_ENABLE=1
    TELEGRAM_API_KEY="12345:ADBSGSASAS"
    TELEGRAM_CHAT_ID="11223344566"
    ```

### CODE REVIEW

**Comment by loayei** [comment]
@coccoinomane any plans to merge this?

**Comment by coccoinomane** [comment]
Hey @yigitest , thank you very much for your contribution: it looks real nice 💪

I am going to review it soon & will probably merge the SMS and IM logging inside the `logger` module.
In this way, we can consider them just as any other logger.

**Comment by yigitest** [comment]
@coccoinomane  Thanks.

I also considered custom logging handlers. But I thought, making a remote/http/post api call inside `ReinforceDefense` would slow things down a bit. i.e. [L56](https://github.com/yigitest/crabada.py/blob/d567548c2889a57674a1080258e8de38d370cfd4/src/bot/mining/reinforceDefense.py#L56) [L67](https://github.com/yigitest/crabada.py/blob/d567548c2889a57674a1080258e8de38d370cfd4/src/bot/mining/reinforceDefense.py#L67). And I did not want to change logging logic.

**Comment by yigitest** [comment]
All is OK.
Thanks again. And your project is easy to code with. That is also an impressive feature.

p.s. sorry about this: `Simplify notification mess (src/bot/mining/reinforceDefense.py)` ;)

**Comment by coccoinomane** [comment]
> All is OK.
> 
> Thanks again. And your project is easy to code with. That is also an impressive feature.
> 
> 
> 
> p.s. sorry about this: `Simplify notification mess (src/bot/mining/reinforceDefense.py)` ;)
> 
> 

Haha 😂 No worries: I was referring to my mess, not yours ;-)

Will merge tomorrow!

**Pull request merged**
