### PR TITLE
Macos changes

### PR DESCRIPTION
**Pull request by JorgePadilla**
Rename some files that were not allowing me to compile.

### CODE REVIEW

**Comment by JorgePadilla** [comment]
Rename files

**Comment by coccoinomane** [comment]
Hi @JorgePadilla and thank you very much for your contribution :-)
May I ask what kind of error you had before changing the file names?
Cheers,
Cocco

**Comment by JorgePadilla** [comment]
No module name found. Also wanted to thank you for your hard work.

**Comment by coccoinomane** [comment]
Thank you very much @JorgePadilla  for the kind words! I have merged the pull request 👍

**Pull request merged**
