### PR TITLE
add tus swap to avax via pangolin

### PR DESCRIPTION
**Pull request by EugeneTeu**
Hi @coccoinomane not sure if you like to include this, but just adding the functionality to swap TUS -> AVAX via the bot. Was writing for my own use so decided might as well just write it in this repo

edit: no tests written because I tested with real money

### CODE REVIEW

**Comment by coccoinomane** [comment]
Wow @EugeneTeu , this is an impressive PR!

I love how you extended the Web3Client to use with Pangolin and TraderJoe: great job 💪

However, I am hesitant to add this to crabada.py.
Swap functionalities are indeed useful, but they go outside the scope of the bot.
It is a lot of code to add tocrabada.py, and we might end up with all sort of issues and support requests: slippage problems, failed swaps, request for other tokens, etc.
I fear this would lead the project astray.

This material is better suited for a separate project, say, `dextools.py`.
A suite of CLI tools to interact with DEXes written in Python, which in principle could support any Uniswap V2 clone.
(I confess that lately I've been working on something similar, but on Javascript.)

If you decide to go ahead with the idea of the separate project, I am happy to make Web3Client an independent `pip` project, so that you can use it as a dependency.

Cheers,
Cocco

**Comment by EugeneTeu** [comment]
sure. After thinking about it, i agree with you on the scope of the bot. For now I will leave this in my fork then! 

on making the Web3Client a `pip` project, that would be great!

**Comment by EugeneTeu** [comment]
sure. After thinking about it, i agree with you on the scope of the bot. For now I will leave this in my fork then! 

on making the Web3Client a `pip` project, that would be great!

**Comment by coccoinomane** [comment]
Thank you @EugeneTeu for your understanding :-)

I will read some material on `pip` and then go ahead with the *Web3Client* project.

Cheers,
Cocco

**Pull request closed without merging**
