### PR TITLE
Alternative to cron and a dockerfile implementation.

### PR DESCRIPTION
**Pull request by yigitest**
## Alternative to cron

For those who don't want to use a cron job; now it is possible to call a single script to run mining operations in an infinite loop.

`python -m bin.mining.run` calls `reinforceDefense`, `closeMines`, and `sendTeamsMining` functions in this order in an infinite loop and sleeps for `SLEEP_TIMER` seconds (defaults to 120) between iterations.

## Dockerfile implementation

I'm also sharing my Dockerfile implementation because, there are couple of changes hard to explain without it :)

* Removed `MissingConfig` error: there is no .env file inside docker.
* I had to use `USER_1_ADDRESS` as `userAddress` parameter in the functions, because command line arguments are not usable in docker setup. So multiuser setup is not supported.

### CODE REVIEW

**Comment by CBSInvest** [comment]
Hi Yigi,
thanks for the contribute, 
i was trying to use MS Power Automate as well as Task Scheduler to get a kind of automation running but maybe because of the Virtual Env i run Python or the created Batch File i created to start the task  i couldn't get it running yet, which kind of additional program should u use if u wanna automate the bot on a Microsoft station.

Well organized me  an old MacPro Laptop today but as i am absolutely not into MAC OS i would love to get it running on my MS Machine, any helpful advice u could share here - thx and appreciate  !

**Comment by yigitest** [comment]
@CBSInvest You can activate your virtualenv and then run python scripts in a bat file. Write a bat script and get it working first. 

After that, you can use Task Scheduler to automate it. There should be an option to specify the folder in which the program will start. Use it to specify the same directory as your new bat-file.

example bat script: `runcrabada.bat`
```
 CALL venv\Scripts\Activate.bat
 python -m bin.mining.closeMines <your address>
 :: or run.py script in this PR will call mining operations indefinitely for you
 :: python -m bin.mining.run
 ```

**Comment by CBSInvest** [comment]
@yigitest Thanks for this tip, i now removed the Virtual enviroment and try to run it without. 

My problem is, i created a bat file as u wrote and all codes are working while double clicking on the bat file or calling it over Command Prompt but to run the bat file over the task sheduler no chance - nothing happens - it makes me nuts cause the file works but automation not - any possible solution ?

**Comment by CBSInvest** [comment]
@yigitest 
Absolutly top, thanks for the help it is running - super - lets focus now on the new tasks to come hope i can contribute enough to enhance the bot - Thank you !!!

**Comment by yigitest** [comment]
@coccoinomane Sorry for the confusing commit history :(
After disabling all storage related stuff (file-logger and Txs) for docker setup, I noticed that you also use it for handling donation and claim logs. 

dockerfile uses a volume mounted to `/storage` (notice the root /) for persistent storage. You don't need to change any configuration, everything is handled with default values via `STORAGE_FOLDER` environment variable. see: [here](https://github.com/coccoinomane/crabada.py/pull/94/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R35-R36) [and here](https://github.com/coccoinomane/crabada.py/pull/94/files#diff-7ff9edf07e1bb9578c8f8f6699d793d5dea64580b532786d36e1d598bb41439eR14)

**Comment by coccoinomane** [comment]
Impressive work @yigitest , as always!
The run.py script will surely help both Windows and non-technical users  💪

As for the Dockerfile, I managed to build the image with `docker build`, but when I try to run it I get the `invalid reference format`. Would you mind sharing your docker commands?

Thanks!
Cocco

**Comment by yigitest** [comment]
On my windows machine (with powershell) I just run: 
```
docker build -t coccoinomane/crabada.py .

docker run  --env-file .env coccoinomane/crabada.py
```

**Comment by coccoinomane** [comment]
Thanks @yigitest , I manage to run the image now 💪

Only issue is that I think the *run.py* command should be in the *bin* folder.
Right now the Docker command fails with `/usr/local/bin/python3: No module named bin.mining.run`

**Comment by coccoinomane** [comment]
@yigitest 

I've split the script in the `bin` and `bot` folder, and added docs to the functions: it works like a charm 😍

There some caveates with `.env`: apparently stuff like double quotes `"` and inline comments `#` are interpreted literally and eventually throw some errors.

Apparently this is a [known issue](https://github.com/docker/compose/issues/3702) of docker, we might get around it by pre-processing _.env_.

**Comment by coccoinomane** [comment]
@yigitest I have merged your PR, thank you again Yigi!

**Pull request merged**
