### PR TITLE
2022.05.1.0

### PR DESCRIPTION
**Pull request by vulogov**

### CODE REVIEW

**Comment by coccoinomane** [comment]
Hi @vulogov!

Sorry I missed your PR, this is the first time I have noticed it.

I understand that your PR allows users to manage private keys using [AWS Secrets Manager](https://docs.aws.amazon.com/crypto/latest/userguide/awscryp-service-sm.html).

The main advantages are:

1. that you do not have to store the private key in the application
2. you can revoke access to the private key using AWS

Am I correct?

Thanks!
Cocco

**Comment by vulogov** [comment]
Yes, I’ve created some tooling that will provide an ability to store private key ether in aws sm or in hashicorp vault

**Comment by coccoinomane** [comment]
Thank you  @vulogov for clarifying!

Is it ok for you if I mention the PR in the Wiki, so that interested people can implement it if they wanted?

Cheers,
Cocco

**Comment by vulogov** [comment]
Sure. There are more in the form of ideas, and Chris Apple will have his words in which of those ideas are “to fly”

V.

**Comment by coccoinomane** [comment]
Thanks @vulogov !

Here's the Wiki article, feel free to modify it if I wrote BS 😉

[🔓 Store private keys remotely](https://github.com/coccoinomane/crabada.py/wiki/%F0%9F%94%93-Store-private-keys-remotely)

Cheers,
Cocco

**Pull request closed without merging**
